window.T = (t) => texts[t] || t;

const texts = {
  'Small Mahjong': 'ちい麻雀',
  Language: '言語',
  'AI oppoents': '対戦 AI 数',
  'Dealt tiles': '配牌数',
  Rounds: '巡回数',
  Start: '開始',
  Home: 'ホーム',
  Reload: '再読込',
  You: 'あなた',
  Alice: 'アリス',
  Bob: 'ボブ',
  Carol: 'キャロル',
  '(D)': '(親)',
  Last: 'オーラス',
  'Reach?': 'リーチ?',
  'Cancel?': '取消?',
  'Tsumo?': 'ツモ?',
  'Tsumo!': 'ツモ!',
  'Reach!': 'リーチ!',
  'Ron!': 'ロン!',
  'Draw the game': '流局',
  'Leave the game?': '退席しますか?',
  Total: '合計',
  Results: '結果',
  'Winner! Winner! Dinner!': '勝った! 勝った! カツ丼だ!',
  Reach: 'リーチ',
  'Double Reach': 'ダブリー',
  'One Shot': 'イッパツ',
  'Last Stock': 'ハイテイ',
  'Last Discard': 'ホウテイ',
  'Win from Stock': 'ツモ',
  'All Middles': 'タンヤオ',
  'All Sequences': 'ピンフ',
  'Pure Double Sequences': 'イーペー',
  'Mixed Triple Sequences': 'サンショク',
  'Mixed Triple Triplets': 'サンドーコー',
  'Pure Straight': 'イッツー',
  'Seven twins': 'チートイ',
  'All Triplets': 'トイトイ',
  'Three Closed Triplets': 'サンアン',
  'All Outside': 'ジュンチャン',
  'Two Pure Double Sequences': 'リャンペー',
  'Full Flush': 'チンイツ',
  'Blessing of Heaven': 'テンホー',
  'Blessing of Earth': 'チーホー',
  'All Terminals': 'チンロー',
  'Four Closed Triplets': 'スーアン',
  'Nine Gates': 'チューレン',
};
